### ISSUE TITLE
don't globally spam all links.

### ISSUE THREAD

**Issue by westonplatter** [jeremyfry/PikaChoose#17]
There are currently CSS rules that all apply to all body and links.

``` css
// transition.css

body {font-family: helvetica, arial, sans-serif;}
a{color:white;}
```

This results in messing up the rest of the site's CSS.

Fix this by only applying the needed body and link CSS rules to PikaChoose specific divs and HTML elements.
